name: premium_ads_v2_example
description: PremiumAds Google AdMob Adapter V2 example app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  premium_ads_v2:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
